# -*- coding: utf-8 -*-
"""demo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10VIMokEOIbA1KxqDGGPh0fcMsukjHv9b
"""

import pandas as pd
import numpy as np
import requests
import math
from bs4 import BeautifulSoup
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
import gradio as gr

# --- 1. MODEL INITIALIZATION (Using Project 38 Parameters) ---
# Referencing "Updated_Report_Project38 (1).docx" for methodology.
try:
    df = pd.read_csv('dataset.csv')
    X = df.drop(columns=['url_url', 'url_url_pre', 'url_url_suf', 'label'])
    y = df['label']

    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(X)

    # Training the Logistic Regression model
    model = LogisticRegression(max_iter=1000)
    model.fit(X_scaled, y)
except FileNotFoundError:
    print("Error: Please upload 'dataset.csv' to Colab first.")

# --- 2. LIVE FEATURE EXTRACTOR ---
def calculate_entropy(text):
    if not text: return 0
    probs = [text.count(c) / len(text) for c in set(text)]
    return -sum(p * math.log2(p) for p in probs)

def extract_features(url):
    try:
        response = requests.get(url, timeout=5)
        soup = BeautifulSoup(response.text, 'html.parser')

        # Mapping extracted data to the 54-feature structure
        features = np.zeros(X.shape[1])

        # URL Lexical Features
        features[0] = len(url) # url_len_url
        features[6] = calculate_entropy(url) # url_pre_entropy

        # Page Content Features
        features[33] = len(response.text) # page_len
        features[34] = len(soup.find_all()) # page_tag_num

        # Security Indicators
        features[41] = len(soup.find_all(attrs={"hidden": True})) # dyn_page_hidden_tag_num
        features[39] = 1 if response.history else 0 # res_is_redirect

        return features.reshape(1, -1)
    except:
        # Fallback if URL is unreachable
        return None

# --- 3. PREDICTION LOGIC ---
def check_url(url):
    if not url.startswith('http'):
        url = 'http://' + url

    data = extract_features(url)
    if data is None:
        return "⚠️ Error: Could not reach the website. Check the URL or your connection."

    scaled_data = scaler.transform(data)
    prediction = model.predict(scaled_data)[0]
    probability = model.predict_proba(scaled_data)[0][1]

    if prediction == 1:
        return f"🚨 PHISHING DETECTED\nConfidence: {probability:.2%}\n\nWarning: This URL shows structural patterns common in malicious spoofing sites."
    else:
        return f"✅ SAFE / LEGITIMATE\nConfidence: {(1-probability):.2%}\n\nThis site appears to be safe based on the Logistic Regression analysis[cite: 1]."

# --- 4. INTERACTIVE INTERFACE ---
demo = gr.Interface(
    fn=check_url,
    inputs=gr.Textbox(placeholder="Enter URL here (e.g., google.com or a suspicious link)"),
    outputs="text",
    title="Project 38: Domain Spoofing & Phishing Detector",
    description="Developed by Seif Zaky Abdallah. This tool uses Machine Learning to analyze URL entropy, hidden tags, and redirects to identify malicious sites[cite: 1]."
)

demo.launch(debug=True)